### ISSUE TITLE
Request with HEAD method runs into timeout

### ISSUE THREAD

**Issue by antonio-rylke-vgl** [byjg/webrequest#3]
HEAD requests are not successful.
Example code:
```php
<?php

require "vendor/autoload.php";

$httpClient = new \ByJG\Util\HttpClient();

$uri = \ByJG\Util\Uri::getInstanceFromString('http://example.com');
$request = \ByJG\Util\Psr7\Request::getInstance($uri)->withMethod('HEAD');

echo $httpClient->sendRequest($request)->getStatusCode() . "\n";
```
When setting `CURLOPT_NOBODY` it works again:
```
$httpClient->withCurlOption(CURLOPT_NOBODY, true);
```
As seen in guzzle: https://github.com/guzzle/guzzle/blob/master/src/Handler/CurlFactory.php#L263

This issue appears in byjg/php-swagger-test.

Thanks a lot.

**Comment by byjg** [comment]
Thank you so much for let me know this issue. I will create the tests and the fix later this week.

**Comment by byjg** [comment]
I added a Unit Test to try to reproduce the error before apply the fix suggested but I couldn't get the timeout. 

Could you provide more details, e.g what header are you providing, http server, etc.

Here is the link for the build job: https://travis-ci.com/github/byjg/webrequest/builds/212546863

**Comment by byjg** [comment]
Never mind. I managed how to reproduce the error and fixed the code. I made a new patch version - `2.0.1`, so you just need to run `composer update` on your project to get the component webrequest fixed.

**Comment by antonio-rylke-vgl** [comment]
Thanks a lot for this fast response and fix!
php-swagger-test is able to test HEAD request.
