### ISSUE TITLE
Default User-Agent is flagged in filter databases

### ISSUE THREAD

**Issue by MrPetovan** [byjg/webrequest#9]
See https://github.com/friendica/friendica/issues/11607#issuecomment-1151429049

**Comment by byjg** [comment]
Thank you for flagging me here. I already applied a patch and now WebRequest uses your own User-Agent (https://github.com/byjg/webrequest/commit/ce441deca57893b3a32edfbb2d21e14a90f6e131)

You can use the release `2.0.4` 

By the way, WebRequest implements the PSR7 pattern. If you want to change the User-Agent you can do this:

```php
<?php
use ByJG\Util\Uri;
use ByJG\Util\Psr7\Request;
use ByJG\Util\HttpClient;
use ByJG\Util\Psr7\MemoryStream;

require "vendor/autoload.php";

$uri = Uri::getInstanceFromString('https://www.whatismybrowser.com/detect/what-is-my-user-agent/');
$request = Request::getInstance($uri)
    ->withHeader("User-Agent", "My custom user agent");
$response = HttpClient::getInstance()->sendRequest($request);

$stream = new MemoryStream($response->getBody());
print_r($stream->getContents());

```

**Comment by MrPetovan** [comment]
Thank you for your reactivity! Unfortunately I don't use WebRequest in this particular project anymore because I needed to instantiate the HTTP client once and perform requests to different URI after that, but I appreciate how fast you changed it.
